POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Damian",
    "phone": "112233"
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Damian",
    "phone": ""
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "",
    "phone": ""
}